name: Build

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout
      id-token: write # to request JWT from GitHub OIDC provider (used in 'gha-prepare-java-build' action)
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # use default aws-role (ci/builder), default java-version (21) and default java-distribution (temurin)
      - name: Setup Java
        uses: agilecustoms/setup-maven-codeartifact@v1
        with:
          aws-account: ${{ vars.AWS_ACCOUNT_DIST }}
          aws-region: 'us-east-1'
          aws-codeartifact-domain: agilecustoms

      - name: Build
        run: mvn --no-transfer-progress verify

      - name: Upload artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v6
        with:
          path: |
            checkstyle-rules/target/**
            openapi/target/**

  Release:
    if: github.ref == 'refs/heads/main'
    needs: Build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write # to request JWT from GitHub OIDC provider (used in 'gha-prepare-java' action)
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v7

      - name: Release
        uses: agilecustoms/release@v5
        with:
          aws-account: ${{ vars.AWS_ACCOUNT_DIST }}
          aws-region: us-east-1
          aws-role: 'ci/publisher'
          aws-codeartifact-maven: publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
