name: Build

on:
  push:
    branches-ignore:
      - main
  workflow_call:
    inputs:
      artifacts:
        required: false
        type: boolean
        default: false
        description: upload artifacts or not

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write # to request JWT from GitHub OIDC provider
      contents: read # required for actions/checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      # Linting, Type checks, tests

      # Package in dist/app.zip

      - name: Upload artifacts
        if: inputs.artifacts
        uses: actions/upload-artifact@v5
        with:
          path: dist/app.zip
